# Generated by Django 5.2.15 on 2026-06-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О мастере (отображается клиентам)'),
        ),
    ]
